package ada95_compilador_10611066;

/* The following code was generated by JFlex 1.4.2 on 09-04-09 03:27 PM */

/**Elementos léxicos del lenguaje de programación ADA-95.
*Autor: Luis Felipe Borjas Reyes @ 25 Agosto 2009
*
*/
/*Correr después del parser!*/
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.2
 * on 09-04-09 03:27 PM from the specification file
 * <tt>ada95_tokens.flex</tt>
 */
class Ada95Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\13\1\0\1\3\1\13\22\0\1\3\1\0\1\11"+
    "\1\5\2\0\1\45\1\14\1\46\1\47\1\50\1\7\1\51\1\10"+
    "\1\6\1\52\12\2\1\53\1\54\1\55\1\56\1\57\2\0\1\23"+
    "\1\26\1\34\1\16\1\15\1\22\1\32\1\41\1\31\1\1\1\42"+
    "\1\24\1\37\1\30\1\27\1\33\1\44\1\20\1\25\1\17\1\21"+
    "\1\43\1\40\1\36\1\35\1\1\4\0\1\4\1\0\1\23\1\26"+
    "\1\34\1\16\1\15\1\22\1\32\1\41\1\31\1\1\1\42\1\24"+
    "\1\37\1\30\1\27\1\33\1\44\1\20\1\25\1\17\1\21\1\12"+
    "\1\40\1\36\1\35\1\1\1\0\1\60\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\4\1\11\23\2\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\5\0\1\31\2\0\1\32\4\2"+
    "\1\33\16\2\1\34\14\2\1\35\1\2\1\36\3\2"+
    "\1\37\1\40\1\41\13\2\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\26\1\0\1\53"+
    "\1\54\1\0\1\55\1\32\1\2\1\56\20\2\1\57"+
    "\3\2\1\60\4\2\1\61\1\2\1\62\1\2\1\63"+
    "\1\2\1\64\12\2\1\65\1\66\1\2\1\67\1\2"+
    "\1\70\5\2\1\71\3\2\1\72\1\73\3\2\1\74"+
    "\1\0\1\75\2\2\1\76\6\2\1\77\1\100\1\2"+
    "\1\101\1\102\17\2\1\103\5\2\1\104\2\2\1\105"+
    "\2\2\1\106\5\2\1\107\1\2\1\110\1\111\1\2"+
    "\2\0\1\112\1\113\1\2\1\114\1\115\11\2\1\116"+
    "\1\117\1\120\1\2\1\121\1\122\2\2\1\123\6\2"+
    "\1\124\12\2\1\125\1\74\1\0\2\2\1\126\1\2"+
    "\1\127\1\2\1\130\1\2\1\131\4\2\1\132\1\133"+
    "\1\2\1\134\3\2\1\135\2\2\1\136\6\2\1\137"+
    "\1\2\1\140\1\141\1\142\1\2\1\143\1\2\1\144"+
    "\1\2\1\145\1\146\1\147\1\150\2\2\1\151\1\152"+
    "\3\2\1\153\1\154\1\155\2\2\1\156\1\157\1\160"+
    "\1\161\1\162";

  private static int [] zzUnpackAction() {
    int [] result = new int[348];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\142"+
    "\0\u0157\0\142\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d"+
    "\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405"+
    "\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c\0\142"+
    "\0\142\0\142\0\u058d\0\142\0\u05be\0\u05ef\0\142\0\u0620"+
    "\0\u0651\0\u0682\0\142\0\u06b3\0\u06e4\0\142\0\u0715\0\u0746"+
    "\0\u0777\0\u07a8\0\u07d9\0\142\0\u080a\0\u083b\0\u083b\0\u086c"+
    "\0\u089d\0\u08ce\0\u08ff\0\223\0\u0930\0\u0961\0\u0992\0\u09c3"+
    "\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b"+
    "\0\u0b7c\0\u0bad\0\223\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2"+
    "\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\223"+
    "\0\u0e2a\0\223\0\u0e5b\0\u0e8c\0\u0ebd\0\223\0\223\0\u0eee"+
    "\0\u0f1f\0\u0f50\0\u0f81\0\u0fb2\0\u0fe3\0\u1014\0\u1045\0\u1076"+
    "\0\u10a7\0\u10d8\0\u1109\0\142\0\142\0\142\0\142\0\142"+
    "\0\142\0\142\0\142\0\142\0\142\0\u113a\0\u116b\0\u119c"+
    "\0\u11cd\0\u080a\0\142\0\u11fe\0\223\0\u122f\0\u1260\0\u1291"+
    "\0\u12c2\0\u12f3\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8\0\u1419"+
    "\0\u144a\0\u147b\0\u14ac\0\u14dd\0\u150e\0\223\0\u153f\0\u1570"+
    "\0\u15a1\0\223\0\u15d2\0\u1603\0\u1634\0\u1665\0\223\0\u1696"+
    "\0\223\0\u16c7\0\u16f8\0\u1729\0\223\0\u175a\0\u178b\0\u17bc"+
    "\0\u17ed\0\u181e\0\u184f\0\u1880\0\u18b1\0\u18e2\0\u1913\0\223"+
    "\0\223\0\u1944\0\223\0\u1975\0\223\0\u19a6\0\u19d7\0\u1a08"+
    "\0\u1a39\0\u1a6a\0\223\0\u1a9b\0\u1acc\0\u1afd\0\223\0\223"+
    "\0\u1b2e\0\u1b5f\0\u1b90\0\u1bc1\0\u1bf2\0\223\0\u1c23\0\u1c54"+
    "\0\223\0\u1c85\0\u1cb6\0\u1ce7\0\u1d18\0\u1d49\0\u1d7a\0\223"+
    "\0\223\0\u1dab\0\223\0\223\0\u1ddc\0\u1e0d\0\u1e3e\0\u1e6f"+
    "\0\u1ea0\0\u1ed1\0\u1f02\0\u1f33\0\u1f64\0\u1f95\0\u1fc6\0\u1ff7"+
    "\0\u2028\0\u2059\0\u208a\0\223\0\u20bb\0\u20ec\0\u211d\0\u214e"+
    "\0\u217f\0\223\0\u21b0\0\u21e1\0\223\0\u2212\0\u2243\0\223"+
    "\0\u2274\0\u22a5\0\u22d6\0\u2307\0\u2338\0\223\0\u2369\0\223"+
    "\0\223\0\u239a\0\u23cb\0\u23fc\0\223\0\223\0\u242d\0\223"+
    "\0\223\0\u245e\0\u248f\0\u24c0\0\u24f1\0\u2522\0\u2553\0\u2584"+
    "\0\u25b5\0\u25e6\0\223\0\223\0\223\0\u2617\0\223\0\223"+
    "\0\u2648\0\u2679\0\223\0\u26aa\0\u26db\0\u270c\0\u273d\0\u276e"+
    "\0\u279f\0\223\0\u27d0\0\u2801\0\u2832\0\u2863\0\u2894\0\u28c5"+
    "\0\u28f6\0\u2927\0\u2958\0\u2989\0\223\0\u29ba\0\u29eb\0\u2a1c"+
    "\0\u2a4d\0\223\0\u2a7e\0\223\0\u2aaf\0\223\0\u2ae0\0\223"+
    "\0\u2b11\0\u2b42\0\u2b73\0\u2ba4\0\223\0\223\0\u2bd5\0\223"+
    "\0\u2c06\0\u2c37\0\u2c68\0\223\0\u2c99\0\u2cca\0\223\0\u2cfb"+
    "\0\u2d2c\0\u2d5d\0\u2d8e\0\u2dbf\0\u2df0\0\223\0\u2e21\0\223"+
    "\0\223\0\223\0\u2e52\0\223\0\u2e83\0\223\0\u2eb4\0\223"+
    "\0\223\0\223\0\223\0\u2ee5\0\u2f16\0\223\0\223\0\u2f47"+
    "\0\u2f78\0\u2fa9\0\223\0\223\0\223\0\u2fda\0\u300b\0\223"+
    "\0\223\0\223\0\223\0\223";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[348];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\3\1\7\1\10\1\11"+
    "\1\12\1\13\1\6\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\4\1\35\1\36\1\37"+
    "\4\4\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\11\54\1\55\1\54"+
    "\1\56\45\54\62\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\30\4\16\0\1\5\1\0\1\60\1\61\1\62"+
    "\6\0\1\63\46\0\1\6\6\0\2\6\53\0\1\64"+
    "\62\0\1\65\51\0\2\4\1\6\1\57\5\0\1\13"+
    "\1\6\1\0\30\4\14\0\14\66\1\67\44\66\1\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\7\4\1\70"+
    "\3\4\1\71\5\4\1\72\6\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\1\73\11\4\1\74\1\4"+
    "\1\75\13\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\1\76\2\4\1\77\2\4\1\100\11\4\1\101"+
    "\3\4\1\102\3\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\1\103\5\4\1\104\21\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\10\4\1\105\2\4"+
    "\1\106\14\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\4\4\1\107\1\4\1\110\1\111\2\4\1\112"+
    "\15\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\2\4\1\113\1\114\3\4\1\115\1\4\1\116\1\4"+
    "\1\117\3\4\1\120\10\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\12\4\1\121\1\4\1\122\13\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\123"+
    "\3\4\1\124\23\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\1\125\11\4\1\126\15\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\2\4\1\127\1\130"+
    "\1\131\1\132\22\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\1\133\3\4\1\134\5\4\1\135\15\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\5\4"+
    "\1\136\2\4\1\137\2\4\1\140\14\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\1\141\11\4\1\142"+
    "\15\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\3\4\1\143\1\144\1\4\1\145\21\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\6\4\1\146\3\4"+
    "\1\147\15\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\12\4\1\150\15\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\12\4\1\151\15\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\14\4\1\152\7\4"+
    "\1\153\3\4\64\0\1\154\66\0\1\155\60\0\1\156"+
    "\57\0\1\157\1\160\1\161\60\0\1\162\57\0\1\163"+
    "\1\164\1\0\11\54\1\0\1\54\1\0\45\54\11\0"+
    "\1\165\50\0\2\4\7\0\1\4\2\0\30\4\16\0"+
    "\1\5\60\0\1\166\12\0\2\166\3\0\2\166\2\0"+
    "\1\166\5\0\1\166\26\0\1\167\60\0\1\170\4\0"+
    "\2\171\50\0\13\65\1\172\45\65\14\0\1\173\45\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\10\4\1\174"+
    "\17\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\4\1\175\1\176\25\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\14\4\1\177\2\4\1\200\10\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\7\4"+
    "\1\201\7\4\1\202\10\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\15\4\1\203\12\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\3\4\1\204\24\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\4\4"+
    "\1\205\23\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\10\4\1\206\4\4\1\207\12\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\16\4\1\210\11\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\211"+
    "\27\4\15\0\2\4\1\0\1\57\5\0\1\212\2\0"+
    "\2\4\1\213\10\4\1\214\3\4\1\215\2\4\1\216"+
    "\3\4\1\212\1\217\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\13\4\1\220\1\221\13\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\1\222\27\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\2\4\1\223"+
    "\25\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\13\4\1\224\14\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\7\4\1\225\20\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\12\4\1\226\15\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\3\4\1\227"+
    "\24\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\3\4\1\230\24\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\7\4\1\231\4\4\1\232\13\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\10\4\1\233"+
    "\1\4\1\234\15\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\1\4\1\235\26\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\17\4\1\236\10\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\12\4\1\237"+
    "\15\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\22\4\1\240\5\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\7\4\1\241\6\4\1\242\11\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\11\4\1\243"+
    "\16\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\15\4\1\244\12\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\1\4\1\245\10\4\1\246\15\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\24\4\1\247"+
    "\3\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\2\4\1\250\25\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\23\4\1\251\4\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\7\4\1\252\20\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\2\4\1\253"+
    "\25\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\2\4\1\254\25\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\2\4\1\255\10\4\1\256\14\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\2\4\1\257"+
    "\25\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\6\4\1\260\3\4\1\261\1\4\1\262\13\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\2\4\1\263"+
    "\25\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\17\4\1\264\10\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\10\4\1\265\17\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\13\4\1\266\14\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\3\4\1\267"+
    "\24\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\4\1\270\26\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\2\4\1\271\25\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\1\272\13\4\1\273\13\4"+
    "\16\0\1\166\1\0\1\61\1\274\1\275\6\0\2\166"+
    "\3\0\2\166\2\0\1\166\5\0\1\166\26\0\1\167"+
    "\1\0\1\62\10\0\1\63\45\0\1\170\1\0\1\171"+
    "\56\0\1\170\57\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\1\276\13\4\1\277\13\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\3\4\1\300\24\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\2\4\1\301"+
    "\25\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\302\27\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\2\4\1\303\3\4\1\304\21\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\7\4\1\305\20\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\14\4"+
    "\1\306\13\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\22\4\1\307\5\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\1\310\27\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\25\4\1\311\2\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\15\4\1\312"+
    "\12\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\313\27\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\13\4\1\314\14\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\1\315\27\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\4\4\1\316\23\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\6\4\1\317"+
    "\21\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\12\4\1\320\15\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\4\4\1\321\23\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\15\4\1\322\12\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\10\4\1\323"+
    "\17\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\14\4\1\324\13\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\17\4\1\325\10\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\10\4\1\205\17\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\6\4\1\326"+
    "\21\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\6\4\1\327\21\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\6\4\1\330\21\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\2\4\1\331\25\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\3\4\1\332"+
    "\24\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\333\27\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\16\4\1\334\11\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\14\4\1\335\13\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\1\336\27\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\6\4\1\337"+
    "\21\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\2\4\1\340\25\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\14\4\1\341\13\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\20\4\1\342\7\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\7\4\1\343"+
    "\20\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\344\27\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\7\4\1\345\20\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\1\346\27\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\1\347\27\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\12\4\1\350\15\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\15\4"+
    "\1\351\12\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\2\4\1\352\14\4\1\353\10\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\354\2\0\26\4\1\354\1\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\25\4"+
    "\1\355\2\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\1\356\27\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\10\4\1\357\17\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\24\4\1\360\3\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\13\4\1\361"+
    "\14\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\7\4\1\362\20\4\31\0\1\363\45\0\1\364\12\0"+
    "\2\364\3\0\2\364\2\0\1\364\5\0\1\364\25\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\5\4\1\365"+
    "\22\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\20\4\1\366\7\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\16\4\1\367\11\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\6\4\1\370\21\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\20\4\1\371"+
    "\7\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\6\4\1\372\21\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\2\4\1\373\25\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\14\4\1\374\13\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\1\375\27\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\3\4"+
    "\1\376\24\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\3\4\1\377\24\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\22\4\1\u0100\5\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\3\4\1\u0101\24\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\u0102"+
    "\27\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\u0103\27\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\1\u0104\27\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\7\4\1\u0105\20\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\2\4\1\u0106\25\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\2\4\1\u0107"+
    "\25\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\20\4\1\u0108\7\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\10\4\1\u0109\17\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\3\4\1\u010a\24\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\2\4\1\u010b"+
    "\25\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\10\4\1\u010c\5\4\1\u010d\11\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\2\4\1\u010e\25\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\17\4\1\u010f"+
    "\10\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\3\4\1\u0110\24\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\20\4\1\u0111\7\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\13\4\1\u0112\14\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\1\u0113\27\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\3\4"+
    "\1\u0114\24\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\15\4\1\u0115\12\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\3\4\1\u0116\24\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\22\4\1\u0117\5\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\u0118"+
    "\27\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\u0119\27\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\6\4\1\u011a\21\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\6\4\1\u011b\21\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\2\4\1\u011c\25\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\u011d"+
    "\27\4\16\0\1\u011e\4\0\2\u011f\52\0\1\364\1\0"+
    "\1\275\1\274\7\0\2\364\3\0\2\364\2\0\1\364"+
    "\5\0\1\364\25\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\2\4\1\u0120\25\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\3\4\1\u0121\24\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\10\4\1\u0122\17\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\13\4"+
    "\1\u0123\14\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\1\4\1\u0124\26\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\10\4\1\u0125\17\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\13\4\1\u0126\14\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\u0127"+
    "\27\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\4\1\u0128\26\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\4\4\1\u0129\23\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\14\4\1\u012a\13\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\1\u012b\27\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\6\4"+
    "\1\u012c\21\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\10\4\1\u012d\17\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\2\4\1\u012e\25\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\1\u012f\27\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\2\4\1\u0130"+
    "\25\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\6\4\1\u0131\21\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\16\4\1\u0132\11\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\6\4\1\u0133\21\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\10\4\1\u0134"+
    "\17\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\u0135\27\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\14\4\1\u0136\13\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\6\4\1\u0137\21\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\17\4\1\u0138\10\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\4"+
    "\1\u0139\26\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\2\4\1\u013a\25\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\15\4\1\u013b\12\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\6\4\1\u013c\21\4"+
    "\16\0\1\u011e\1\0\1\u011f\56\0\1\u011e\57\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\14\4\1\u013d\13\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\u013e"+
    "\27\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\6\4\1\u013f\21\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\1\u0140\27\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\10\4\1\u0141\17\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\1\u0142\27\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\12\4\1\u0143"+
    "\15\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\4\1\u0144\26\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\17\4\1\u0145\10\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\1\4\1\u0146\26\4\15\0"+
    "\2\4\1\0\1\57\5\0\1\4\2\0\2\4\1\u0147"+
    "\25\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\u0148\27\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\13\4\1\u0149\14\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\3\4\1\u014a\24\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\17\4\1\u014b\10\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\2\4"+
    "\1\u014c\25\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\4\4\1\u014d\23\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\1\u014e\27\4\15\0\2\4\1\0"+
    "\1\57\5\0\1\4\2\0\1\u014f\27\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\13\4\1\u0150\14\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\12\4"+
    "\1\u0151\15\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\2\4\1\u0152\25\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\13\4\1\u0153\14\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\2\4\1\u0154\25\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\u0155"+
    "\27\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\u0156\27\4\15\0\2\4\1\0\1\57\5\0\1\4"+
    "\2\0\3\4\1\u0157\24\4\15\0\2\4\1\0\1\57"+
    "\5\0\1\4\2\0\2\4\1\u0158\25\4\15\0\2\4"+
    "\1\0\1\57\5\0\1\4\2\0\13\4\1\u0159\14\4"+
    "\15\0\2\4\1\0\1\57\5\0\1\4\2\0\1\u015a"+
    "\27\4\15\0\2\4\1\0\1\57\5\0\1\4\2\0"+
    "\1\4\1\u015b\26\4\15\0\2\4\1\0\1\57\5\0"+
    "\1\4\2\0\1\u015c\27\4\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12348];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\4\1\1\11\1\1\1\11\25\1\3\11"+
    "\1\1\1\11\2\1\1\11\3\1\1\11\2\1\1\11"+
    "\5\0\1\11\2\0\65\1\12\11\1\0\2\1\1\0"+
    "\1\1\1\11\101\1\1\0\65\1\2\0\52\1\1\0"+
    "\75\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[348];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
StringBuffer string=new StringBuffer();
/**Función para crear un nuevo símbolo de java_cup.runtime vacío*/
private Symbol symbol(int type){
	return new Symbol(type,yyline,yycolumn);
}

/**Función para crear un nuevo símbolo de java_cup.runtime con valor
*@ param value el valor del símbolo
*/
private Symbol symbol(int type, Object value){
	return new Symbol(type, yyline, yycolumn, value);
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Ada95Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Ada95Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 112: 
          { return symbol(sym.TERMINATE);
          }
        case 115: break;
        case 65: 
          { return symbol(sym.TYPE);
          }
        case 116: break;
        case 38: 
          { return symbol(sym.LTEQ);
          }
        case 117: break;
        case 59: 
          { return symbol(sym.MOD);
          }
        case 118: break;
        case 33: 
          { return symbol(sym.IN);
          }
        case 119: break;
        case 3: 
          { return symbol(sym.INTEGER_LITERAL,new Integer(Integer.parseInt(yytext().replaceAll("_",""))));
          }
        case 120: break;
        case 108: 
          { return symbol(sym.ABSTRACT);
          }
        case 121: break;
        case 45: 
          { /*ignorar*/
          }
        case 122: break;
        case 78: 
          { return symbol(sym.RANGE);
          }
        case 123: break;
        case 29: 
          { return symbol(sym.OR);
          }
        case 124: break;
        case 10: 
          { return symbol(sym.CONCATENATE);
          }
        case 125: break;
        case 91: 
          { return symbol(sym.ACCEPT);
          }
        case 126: break;
        case 73: 
          { return symbol(sym.WHEN);
          }
        case 127: break;
        case 57: 
          { return symbol(sym.PUT);
          }
        case 128: break;
        case 68: 
          { return symbol(sym.BODY);
          }
        case 129: break;
        case 8: 
          { string.setLength(0);yybegin(STRING);
          }
        case 130: break;
        case 82: 
          { return symbol(sym.ARRAY);
          }
        case 131: break;
        case 11: 
          { return symbol(sym.LEFTPAR);
          }
        case 132: break;
        case 81: 
          { return symbol(sym.FLOAT);
          }
        case 133: break;
        case 7: 
          { return symbol(sym.MINUS);
          }
        case 134: break;
        case 25: 
          { return symbol(sym.DOUBLEDOT);
          }
        case 135: break;
        case 74: 
          { return symbol(sym.ELSIF);
          }
        case 136: break;
        case 17: 
          { return symbol(sym.SEMICOLON);
          }
        case 137: break;
        case 61: 
          { return symbol(sym.ELSE);
          }
        case 138: break;
        case 62: 
          { return symbol(sym.EXIT);
          }
        case 139: break;
        case 19: 
          { return symbol(sym.EQUAL);
          }
        case 140: break;
        case 37: 
          { return symbol(sym.LEFTLABEL);
          }
        case 141: break;
        case 98: 
          { return symbol(sym.REQUEUE);
          }
        case 142: break;
        case 97: 
          { return symbol(sym.RENAMES);
          }
        case 143: break;
        case 36: 
          { return symbol(sym.ASSIGNMENT);
          }
        case 144: break;
        case 5: 
          { return symbol(sym.POINT);
          }
        case 145: break;
        case 80: 
          { return symbol(sym.UNTIL);
          }
        case 146: break;
        case 90: 
          { return symbol(sym.ACCESS);
          }
        case 147: break;
        case 23: 
          { yybegin(YYINITIAL);
	 return symbol(sym.STRING_LITERAL,string.toString());
          }
        case 148: break;
        case 111: 
          { return symbol(sym.EXCEPTION);
          }
        case 149: break;
        case 41: 
          { return symbol(sym.GTEQ);
          }
        case 150: break;
        case 16: 
          { return symbol(sym.COLON);
          }
        case 151: break;
        case 67: 
          { return symbol(sym.LOOP);
          }
        case 152: break;
        case 52: 
          { return symbol(sym.AND);
          }
        case 153: break;
        case 92: 
          { return symbol(sym.SELECT);
          }
        case 154: break;
        case 113: 
          { return symbol(sym.PROTECTED);
          }
        case 155: break;
        case 94: 
          { return symbol(sym.PRAGMA);
          }
        case 156: break;
        case 53: 
          { return symbol(sym.OUT);
          }
        case 157: break;
        case 96: 
          { return symbol(sym.REVERSE);
          }
        case 158: break;
        case 31: 
          { return symbol(sym.IF);
          }
        case 159: break;
        case 1: 
          { /*throw new Error("Caracter inesperado: <"+yytext()+"> en línea "+yyline+", columna "+yycolumn);*/
	System.err.println("Caracter inesperado: <"+yytext()+"> en línea "+yyline+", columna "+yycolumn);
          }
        case 160: break;
        case 55: 
          { return symbol(sym.NOT);
          }
        case 161: break;
        case 79: 
          { return symbol(sym.RAISE);
          }
        case 162: break;
        case 12: 
          { return symbol(sym.RIGHTPAR);
          }
        case 163: break;
        case 104: 
          { return symbol(sym.GENERIC);
          }
        case 164: break;
        case 85: 
          { return symbol(sym.WHILE);
          }
        case 165: break;
        case 56: 
          { return symbol(sym.GET);
          }
        case 166: break;
        case 26: 
          { return symbol(sym.CHARACTER_LITERAL,yytext());
          }
        case 167: break;
        case 95: 
          { return symbol(sym.DECLARE);
          }
        case 168: break;
        case 14: 
          { return symbol(sym.COMMA);
          }
        case 169: break;
        case 64: 
          { return symbol(sym.TASK);
          }
        case 170: break;
        case 89: 
          { return symbol(sym.RECORD);
          }
        case 171: break;
        case 86: 
          { return symbol(sym.DIGITS);
          }
        case 172: break;
        case 35: 
          { return symbol(sym.INEQUALITY);
          }
        case 173: break;
        case 39: 
          { return symbol(sym.BOX);
          }
        case 174: break;
        case 30: 
          { return symbol(sym.OF);
          }
        case 175: break;
        case 51: 
          { return symbol(sym.ABS);
          }
        case 176: break;
        case 102: 
          { return symbol(sym.BOOLEAN);
          }
        case 177: break;
        case 69: 
          { return symbol(sym.NULL);
          }
        case 178: break;
        case 9: 
          { return symbol(sym.TICK);
          }
        case 179: break;
        case 72: 
          { return symbol(sym.WITH);
          }
        case 180: break;
        case 22: 
          { string.append(yytext());
          }
        case 181: break;
        case 46: 
          { return symbol(sym.END);
          }
        case 182: break;
        case 58: 
          { return symbol(sym.XOR);
          }
        case 183: break;
        case 44: 
          { System.err.println("<"+yytext()+"> Es un número con exponente, este compilador sólo acepta números enteros y de punto flotante sin exponente");
          }
        case 184: break;
        case 6: 
          { return symbol(sym.PLUS);
          }
        case 185: break;
        case 93: 
          { return symbol(sym.OTHERS);
          }
        case 186: break;
        case 47: 
          { return symbol(sym.REM);
          }
        case 187: break;
        case 60: 
          { System.err.println("<"+yytext()+"> Es un número con base, este compilador sólo acepta números enteros y de punto flotante sin exponente");
          }
        case 188: break;
        case 40: 
          { return symbol(sym.ARROW);
          }
        case 189: break;
        case 48: 
          { return symbol(sym.USE);
          }
        case 190: break;
        case 84: 
          { return symbol(sym.BEGIN);
          }
        case 191: break;
        case 70: 
          { return symbol(sym.GOTO);
          }
        case 192: break;
        case 4: 
          { /*return symbol(sym.SEPARATOR);*/
          }
        case 193: break;
        case 66: 
          { return symbol(sym.THEN);
          }
        case 194: break;
        case 42: 
          { return symbol(sym.RIGHTLABEL);
          }
        case 195: break;
        case 105: 
          { return symbol(sym.PRIVATE);
          }
        case 196: break;
        case 34: 
          { return symbol(sym.EXPONENTIATE);
          }
        case 197: break;
        case 114: 
          { return symbol(sym.PROCEDURE);
          }
        case 198: break;
        case 88: 
          { return symbol(sym.RETURN);
          }
        case 199: break;
        case 43: 
          { return symbol(sym.FLOATING_POINT_LITERAL,new Float(Float.parseFloat(yytext().replaceAll("_",""))));
          }
        case 200: break;
        case 28: 
          { return symbol(sym.AT);
          }
        case 201: break;
        case 106: 
          { return symbol(sym.PACKAGE);
          }
        case 202: break;
        case 107: 
          { return symbol(sym.FUNCTION);
          }
        case 203: break;
        case 110: 
          { return symbol(sym.CONSTANT);
          }
        case 204: break;
        case 77: 
          { return symbol(sym.DELAY);
          }
        case 205: break;
        case 99: 
          { return symbol(sym.ALIASED);
          }
        case 206: break;
        case 24: 
          { System.err.println("Error léxico: no es permitido un salto de línea en una cadena de caracteres. En línea "+yyline+", columna "+yycolumn);
          }
        case 207: break;
        case 101: 
          { return symbol(sym.SUBTYPE);
          }
        case 208: break;
        case 15: 
          { return symbol(sym.DIVIDE);
          }
        case 209: break;
        case 20: 
          { return symbol(sym.GT);
          }
        case 210: break;
        case 100: 
          { return symbol(sym.LIMITED);
          }
        case 211: break;
        case 109: 
          { return symbol(sym.SEPARATE);
          }
        case 212: break;
        case 87: 
          { return symbol(sym.TAGGED);
          }
        case 213: break;
        case 27: 
          { return symbol(sym.DO);
          }
        case 214: break;
        case 49: 
          { return symbol(sym.FOR);
          }
        case 215: break;
        case 32: 
          { return symbol(sym.IS);
          }
        case 216: break;
        case 83: 
          { return symbol(sym.ABORT);
          }
        case 217: break;
        case 21: 
          { return symbol(sym.VERTICAL_LINE);
          }
        case 218: break;
        case 13: 
          { return symbol(sym.MULTIPLY);
          }
        case 219: break;
        case 71: 
          { return symbol(sym.CASE);
          }
        case 220: break;
        case 75: 
          { return symbol(sym.ENTRY);
          }
        case 221: break;
        case 63: 
          { return symbol(sym.BOOLEAN_LITERAL,new Boolean(Boolean.parseBoolean(yytext())));
          }
        case 222: break;
        case 103: 
          { return symbol(sym.INTEGER);
          }
        case 223: break;
        case 18: 
          { return symbol(sym.LT);
          }
        case 224: break;
        case 50: 
          { return symbol(sym.ALL);
          }
        case 225: break;
        case 76: 
          { return symbol(sym.DELTA);
          }
        case 226: break;
        case 54: 
          { return symbol(sym.NEW);
          }
        case 227: break;
        case 2: 
          { return symbol(sym.IDENTIFIER, yytext());
          }
        case 228: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
